### ISSUE TITLE
The webcam-example.py doesn't run

### ISSUE THREAD

**Issue by JohnCC330** [brettviren/pygst-tutorial-org#3]
Running the example doesn't show any image on screen, and produces the following (non-fatal) error message:

```
Error: gst-stream-error-quark: Internal data stream error. (1) gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
```

From debugging I see the following:

0:00:08.245975521  9271      0x1e19390 INFO        GST_ELEMENT_PADS gstpad.c:2134:gst_pad_unlink: unlinking sink:proxypad0(0x24640f0) and autovideosink0-actual-sink-xvimage:sink(0x2460530)
0:00:08.246004103  9271      0x1e19390 INFO        GST_ELEMENT_PADS gstpad.c:2188:gst_pad_unlink: unlinked sink:proxypad0 and autovideosink0-actual-sink-xvimage:sink
0:00:08.246026885  9271      0x1e19390 INFO           GST_PARENTAGE gstbin.c:1799:gst_bin_remove_func:<autovideosink0> removed child "autovideosink0-actual-sink-xvimage"
0:00:08.246081196  9271      0x1e19390 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:359:gst_element_factory_create: creating element "fakesink" named "fake-video-sink"
0:00:08.246152803  9271      0x1e19390 INFO        GST_ELEMENT_PADS gstelement.c:670:gst_element_add_pad:<GstBaseSink@0x21c11e0> adding pad 'sink'
0:00:08.246215745  9271      0x1e19390 INFO        GST_ELEMENT_PADS gstelement.c:920:gst_element_get_static_pad: found pad fake-video-sink:sink
0:00:08.246244692  9271      0x1e19390 INFO                GST_PADS gstpad.c:2378:gst_pad_link_prepare: trying to link sink:proxypad0 and fake-video-sink:sink
0:00:08.246272559  9271      0x1e19390 INFO                GST_PADS gstpad.c:2586:gst_pad_link_full: linked sink:proxypad0 and fake-video-sink:sink, successful
0:00:08.246291710  9271      0x1e19390 INFO               GST_EVENT gstevent.c:1517:gst_event_new_reconfigure: creating reconfigure event
0:00:08.246313712  9271      0x1e19390 INFO               GST_EVENT gstpad.c:5785:gst_pad_send_event_unchecked:<sink:proxypad0> Received event on flushing pad. D

Which I think suggests that autovideosink doesn't like the configuration.

**Comment by vmx** [comment]
For me it worked, when I added `videoconvert` to the pipeline:

```diff
--- a/webcam-example.py
+++ b/webcam-example.py
@@ -30,7 +30,7 @@ class GTK_Main:
         window.show_all()
 
         # Set up the gstreamer pipeline
-        self.player = Gst.parse_launch ("v4l2src ! autovideosink")
+        self.player = Gst.parse_launch ("v4l2src ! videoconvert ! autovideosink")
         bus = self.player.get_bus()
```

**Comment by JohnCC330** [comment]
Thanks!
Maybe someone will pick this up and update the example?
