### ISSUE TITLE
Glaring omission

### ISSUE THREAD

**Issue by j3pic** [brettviren/pygst-tutorial-org#4]
How exactly do you install "pygst"? I've tried the following:

    pip3 install pygst
    pip3 install gi
    pip3 install python-gst

**Comment by brettviren** [comment]
This is a tutorial document.  You install it by reading it.

**Comment by j3pic** [comment]
The tutorial document assumes the presence of things that are not installed on my system. What do you install so that `import gi` will work? That should be in the tutorial.

**Comment by brettviren** [comment]
On Ubuntu the package is called `python-gi`.
